### PR TITLE
Initiate class structure: Create LMSMaster class

### PR DESCRIPTION
**Pull request by ritesh-rapidops**

### CODE REVIEW

**Comment by joy-gohil** [comment]
everything seems intact.
Merge the file to master

**Comment by ritesh-rapidops** [comment]
Okay then
I'll create other classes and then we will **merge** this branch into **dev** after an another review.

**Comment by joy-gohil** [comment]
cool! lets get started then

**Comment by ritesh-rapidops** [comment]
Sorry, pushed from different account by mistake. I'll take care of that next time.

**Comment by ritesh-rapidops** [comment]
Review this and if all okay, then merge this branch

**Comment by ritesh-rapidops** [comment]
But don't remove this branch

**Pull request merged**
